name: Deploy
on:
  push:
    branches: [ "main" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Install
        run: cd functions && npm install

      - name: Build
        run: cd functions && npm run build

      - name: Archive Production Artifact
        uses: actions/upload-artifact@main
        with:
          name: telebot
          path: functions/lib/index.js
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
        
      - name: Download Artifact
        uses: actions/download-artifact@main
        with:
          name: telebot
          path: functions/lib/index.js

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
